"""add entities and relationships tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-26 16:46:29.912002

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: str | Sequence[str] | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'entity_type', name='uq_entities_name_type')
    )
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_entity_id', sa.Integer(), nullable=False),
    sa.Column('to_entity_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['to_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: autogenerate again proposed dropping ix_chunks_content_trgm and
    # ix_chunks_embedding_hnsw — the same recurring false positive noted in
    # 0004 (those indexes are real, created via raw SQL in 0003, just not
    # visible to SQLAlchemy's metadata diff). Removed those two lines.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('entities')
    # ### end Alembic commands ###
