"""add research reports table

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-26 16:55:09.487954

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: str | Sequence[str] | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('references_json', sa.Text(), nullable=False),
    sa.Column('unverifiable_reference_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: same recurring autogenerate false positive as 0004/0005 —
    # ix_chunks_content_trgm/ix_chunks_embedding_hnsw are real (raw SQL in
    # 0003) but invisible to SQLAlchemy's metadata diff. Lines removed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_reports')
    # ### end Alembic commands ###
