"""add opportunities table

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-26 17:04:40.248578

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: str | Sequence[str] | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('feasibility', sa.String(length=8), nullable=False),
    sa.Column('strategic_value', sa.String(length=32), nullable=False),
    sa.Column('weighted_score', sa.Integer(), nullable=False),
    sa.Column('tech_summary', sa.Text(), nullable=False),
    sa.Column('timeline', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.Text(), nullable=False),
    sa.Column('source_section', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: same recurring autogenerate false positive as 0004-0006 —
    # ix_chunks_content_trgm/ix_chunks_embedding_hnsw are real (raw SQL in
    # 0003) but invisible to SQLAlchemy's metadata diff. Lines removed.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('opportunities')
    # ### end Alembic commands ###
